version: 4.1.0.{build}

configuration: Release

os: Visual Studio 2017

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

install:
  - cmd: choco install dotnetcore-sdk -y

before_build:
  - dotnet --info

build_script:
- cmd: >-
    rake ci
test: off

artifacts:
  - path: '**\Lamar*.nupkg' # find all NuGet packages recursively
