version: 0.8.5.{build}

configuration: Release

os: Visual Studio 2017

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true



before_build:
  - dotnet --info

build_script:
- cmd: >-
    rake ci
test: off

artifacts:
  - path: '**\Lamar.*.nupkg' # find all NuGet packages recursively
