name: Publish Lamar IoC Nugets

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET 10
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 10.0.x
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build Lamar.sln --configuration Release

    - name: Publish Lamar
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/Lamar/Lamar.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Lamar.Microsoft.DependencyInjection
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: src/Lamar.Microsoft.DependencyInjection/Lamar.Microsoft.DependencyInjection.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
