name: Publish Lamar Code Generation Nugets

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build Lamar.sln --configuration Release

    - name: Publish LamarCodeGeneration
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/LamarCodeGeneration/LamarCodeGeneration.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish LamarCodeGeneration.Commands
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: src/LamarCodeGeneration.Commands/LamarCodeGeneration.Commands.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish LamarCompiler
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: src/LamarCompiler/LamarCompiler.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}